# Generated by Django 4.0.5 on 2022-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacao',
            name='operacao',
            field=models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], default='c', max_length=1),
            preserve_default=False,
        ),
    ]
